#1.Perform exploratory data analysis (EDA) to gain insights into the dataset. Provide visualizations and summary statistics of the variables. Pre process the data to apply the MLR.

In [3]:
import pandas as pd
df=pd.read_csv(r"C:\Users\nares.LAP\OneDrive\Toyotta Corolla.csv")
df
#What is Multiple Linear Regression
#Multiple Linear Regression (MLR) is a statistical technique used to model the relationship between a dependent variable and multiple independent variables (predictors or features). It is an extension of simple linear regression, where instead of one independent variable, we use multiple independent variables to predict the outcome.

#Explanation:
#1.Understand the Dataset:
#Check the structure of the data, including the columns, data types, and number of rows.
#Summarize the dataset to understand the distribution of numerical variables and identify potential anomalies or trends.

#2. Handle Missing Data:
#Identify missing values in the dataset.
#Decide on how to handle missing values (e.g., removing rows/columns or imputing values with mean, median, or mode).

#3.Explore Data Relationships:
#Use visualizations to understand the relationships between variables:
#Histograms: Show the distribution of numerical variables.
#Correlation Heatmaps: Indicate relationships between features and the target variable.
#Pairplots: Highlight trends or patterns in data.

#4.Detect and Handle Outliers:
#Use boxplots to identify outliers in numerical data.
#Decide whether to remove outliers or transform them to reduce their impact on the model.

#5.Check Multicollinearity:
#Multicollinearity occurs when independent variables are highly correlated. This can reduce the model’s effectiveness.
#Identify multicollinearity using metrics like the Variance Inflation Factor (VIF) and decide whether to drop or combine correlated variables.

#6.Encode Categorical Variables:
#Convert categorical variables into numerical formats using techniques like one-hot encoding or label encoding to make them usable in regression analysis.

#7.Scale the Features:
#Standardize or normalize the numerical features to ensure they have comparable ranges. This helps improve the model’s performance, especially when features have different units or scales.

#8.Split the Data:
#Divide the dataset into training and testing sets to evaluate the model effectively. Typically, 70-80% is used for training, and 20-30% is for testing.

#9. Apply MLR:
#Fit the Multiple Linear Regression model to the training data.
#Evaluate its performance on the test set using metrics like Mean Squared Error (MSE) and R-squared to measure accuracy.

,Price,Age_08_04,KM,Fuel_Type,HP,Automatic,cc,Doors,Cylinders,Gears,Weight
0,13500,23,46986,Diesel,90,0,2000,3,4,5,1165
1,13750,23,72937,Diesel,90,0,2000,3,4,5,1165
2,13950,24,41711,Diesel,90,0,2000,3,4,5,1165
3,14950,26,48000,Diesel,90,0,2000,3,4,5,1165
4,13750,30,38500,Diesel,90,0,2000,3,4,5,1170
...,...,...,...,...,...,...,...,...,...,...,...
1431,7500,69,20544,Petrol,86,0,1300,3,4,5,1025
1432,10845,72,19000,Petrol,86,0,1300,3,4,5,1015
1433,8500,71,17016,Petrol,86,0,1300,3,4,5,1015
1434,7250,70,16916,Petrol,86,0,1300,3,4,5,1015
1435,6950,76,1,Petrol,110,0,1600,5,4,5,1114

In [4]:
df.shape

(1436, 11)

In [5]:
df.describe()

,Price,Age_08_04,KM,HP,Automatic,cc,Doors,Cylinders,Gears,Weight
count,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.00000,1436.000000,1436.0,1436.000000,1436.00000
mean,10730.824513,55.947075,68533.259749,101.502089,0.055710,1576.85585,4.033426,4.0,5.026462,1072.45961
std,3626.964585,18.599988,37506.448872,14.981080,0.229441,424.38677,0.952677,0.0,0.188510,52.64112
min,4350.000000,1.000000,1.000000,69.000000,0.000000,1300.00000,2.000000,4.0,3.000000,1000.00000
25%,8450.000000,44.000000,43000.000000,90.000000,0.000000,1400.00000,3.000000,4.0,5.000000,1040.00000
50%,9900.000000,61.000000,63389.500000,110.000000,0.000000,1600.00000,4.000000,4.0,5.000000,1070.00000
75%,11950.000000,70.000000,87020.750000,110.000000,0.000000,1600.00000,5.000000,4.0,5.000000,1085.00000
max,32500.000000,80.000000,243000.000000,192.000000,1.000000,16000.00000,5.000000,4.0,6.000000,1615.00000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Price      1436 non-null   int64
 1   Age_08_04  1436 non-null   int64
 2   KM         1436 non-null   int64
 3   Fuel_Type  1436 non-null   object
 4   HP         1436 non-null   int64
 5   Automatic  1436 non-null   int64
 6   cc         1436 non-null   int64
 7   Doors      1436 non-null   int64
 8   Cylinders  1436 non-null   int64
 9   Gears      1436 non-null   int64
 10  Weight     1436 non-null   int64
dtypes: int64(10), object(1)
memory usage: 123.5+ KB

In [7]:
df.columns

Index(['Price', 'Age_08_04', 'KM', 'Fuel_Type', 'HP', 'Automatic', 'cc',
       'Doors', 'Cylinders', 'Gears', 'Weight'],
      dtype='object')

In [8]:
df.head()

,Price,Age_08_04,KM,Fuel_Type,HP,Automatic,cc,Doors,Cylinders,Gears,Weight
0,13500,23,46986,Diesel,90,0,2000,3,4,5,1165
1,13750,23,72937,Diesel,90,0,2000,3,4,5,1165
2,13950,24,41711,Diesel,90,0,2000,3,4,5,1165
3,14950,26,48000,Diesel,90,0,2000,3,4,5,1165
4,13750,30,38500,Diesel,90,0,2000,3,4,5,1170

In [9]:
df.tail()

,Price,Age_08_04,KM,Fuel_Type,HP,Automatic,cc,Doors,Cylinders,Gears,Weight
1431,7500,69,20544,Petrol,86,0,1300,3,4,5,1025
1432,10845,72,19000,Petrol,86,0,1300,3,4,5,1015
1433,8500,71,17016,Petrol,86,0,1300,3,4,5,1015
1434,7250,70,16916,Petrol,86,0,1300,3,4,5,1015
1435,6950,76,1,Petrol,110,0,1600,5,4,5,1114

In [10]:
df.corr

<bound method DataFrame.corr of       Price  Age_08_04     KM Fuel_Type   HP  Automatic    cc  Doors  \
0     13500         23  46986    Diesel   90          0  2000      3
1     13750         23  72937    Diesel   90          0  2000      3
2     13950         24  41711    Diesel   90          0  2000      3
3     14950         26  48000    Diesel   90          0  2000      3
4     13750         30  38500    Diesel   90          0  2000      3
...     ...        ...    ...       ...  ...        ...   ...    ...
1431   7500         69  20544    Petrol   86          0  1300      3
1432  10845         72  19000    Petrol   86          0  1300      3
1433   8500         71  17016    Petrol   86          0  1300      3
1434   7250         70  16916    Petrol   86          0  1300      3
1435   6950         76      1    Petrol  110          0  1600      5

      Cylinders  Gears  Weight
0             4      5    1165
1             4      5    1165
2             4      5    1165
3             4      5    1165
4             4      5    1170
...         ...    ...     ...
1431          4      5    1025
1432          4      5    1015
1433          4      5    1015
1434          4      5    1015
1435          4      5    1114

[1436 rows x 11 columns]>

In [11]:
df.dtypes

Price         int64
Age_08_04     int64
KM            int64
Fuel_Type    object
HP            int64
Automatic     int64
cc            int64
Doors         int64
Cylinders     int64
Gears         int64
Weight        int64
dtype: object

In [12]:
df.isnull().sum()

Price        0
Age_08_04    0
KM           0
Fuel_Type    0
HP           0
Automatic    0
cc           0
Doors        0
Cylinders    0
Gears        0
Weight       0
dtype: int64

In [13]:
df.isna().sum()

Price        0
Age_08_04    0
KM           0
Fuel_Type    0
HP           0
Automatic    0
cc           0
Doors        0
Cylinders    0
Gears        0
Weight       0
dtype: int64

In [14]:
df.dropna()

,Price,Age_08_04,KM,Fuel_Type,HP,Automatic,cc,Doors,Cylinders,Gears,Weight
0,13500,23,46986,Diesel,90,0,2000,3,4,5,1165
1,13750,23,72937,Diesel,90,0,2000,3,4,5,1165
2,13950,24,41711,Diesel,90,0,2000,3,4,5,1165
3,14950,26,48000,Diesel,90,0,2000,3,4,5,1165
4,13750,30,38500,Diesel,90,0,2000,3,4,5,1170
...,...,...,...,...,...,...,...,...,...,...,...
1431,7500,69,20544,Petrol,86,0,1300,3,4,5,1025
1432,10845,72,19000,Petrol,86,0,1300,3,4,5,1015
1433,8500,71,17016,Petrol,86,0,1300,3,4,5,1015
1434,7250,70,16916,Petrol,86,0,1300,3,4,5,1015
1435,6950,76,1,Petrol,110,0,1600,5,4,5,1114

In [15]:
df.cleaned=df.dropna()

C:\Users\nares.LAP\AppData\Local\Temp\ipykernel_23256\3541197218.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.cleaned=df.dropna()

#2.Split the dataset into training and testing sets (e.g., 80% training, 20% testing).

In [16]:
# Importing necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import seaborn as sns
import matplotlib.pyplot as plt

# Load the dataset
data = pd.read_csv(r'//content/ToyotaCorolla - MLR.csv')

# Display basic information about the dataset
print("Dataset Info:")
print(data.info())

# Display the first few rows of the dataset
print("\nFirst Few Rows of the Dataset:")
print(data.head())

# Step 1: Handle Outliers in the 'cc' column
# Capping outliers at the 99th percentile
cc_threshold = data['cc'].quantile(0.99)
data['cc'] = data['cc'].clip(upper=cc_threshold)
print("\nUpdated 'cc' column after capping outliers:")
print(data['cc'].describe())

# Step 2: Encode Categorical Variables
# Encoding 'Fuel_Type' column using one-hot encoding
data = pd.get_dummies(data, columns=['Fuel_Type'], drop_first=True)

# Step 3: Define Features and Target Variable
X = data.drop(columns=['Price'])  # Independent variables
y = data['Price']  # Dependent variable

# Step 4: Scale the Features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Step 5: Split the Data into Training and Testing Sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Step 6: Display Shapes of Resulting Datasets
print("\nShape of Training and Testing Sets:")
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

# Step 7: Visualize Correlations Between Variables
print("\nCorrelation Heatmap:")
plt.figure(figsize=(10, 8))
sns.heatmap(data.corr(), annot=True, cmap="coolwarm", fmt=".2f", linewidths=0.5)
plt.title("Correlation Heatmap", fontsize=16)
plt.show()

# Step 8: Visualize Distributions of Numerical Variables
print("\nHistograms of Numerical Variables:")
data.select_dtypes(include=['int64', 'float64']).hist(bins=20, figsize=(15, 10), color='skyblue', edgecolor='black')
plt.suptitle("Distributions of Numerical Variables", fontsize=16)
plt.show()

#Explanation:
#1.Data Loading and Inspection:
#Load the dataset and inspect its structure with info() and head().

#2.Outlier Handling:
#Capped extreme values in the cc column at the 99th percentile to mitigate their influence.

#3.Encoding Categorical Variables:
#Used one-hot encoding to convert the categorical Fuel_Type column into numerical variables.

#4.Feature Scaling:
#Standardized numerical features to bring them to a comparable scale.

#5.Train-Test Split:
#Divided the data into 80% training and 20% testing subsets for modeling and evaluation.

#6.Visualizations:
#Created a correlation heatmap to identify relationships between variables.
#Plotted histograms to examine the distribution of numerical variables.

FileNotFoundError: [Errno 2] No such file or directory: '//content/ToyotaCorolla - MLR.csv'

#3.Build a multiple linear regression model using the training dataset. Interpret the coefficients of the model. Build minimum of 3 different models.

In [ ]:
# Import required libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score

# Step 1: Load the dataset
# Example: Using California housing dataset from sklearn
from sklearn.datasets import fetch_california_housing
data = fetch_california_housing()
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target

# Step 2: Preprocess the data
# Split the data into features (X) and target (y)
X = df.drop(columns='target')
y = df['target']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Optional: Standardize the data (for better model performance in some cases)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Step 3: Train three different multiple linear regression models

# Model 1: Basic Linear Regression
model1 = LinearRegression()
model1.fit(X_train, y_train)
y_pred1 = model1.predict(X_test)

# Model 2: Linear Regression with regularization (Ridge)
from sklearn.linear_model import Ridge
model2 = Ridge(alpha=1.0)
model2.fit(X_train, y_train)
y_pred2 = model2.predict(X_test)

# Model 3: Linear Regression with Lasso regularization
from sklearn.linear_model import Lasso
model3 = Lasso(alpha=0.1)
model3.fit(X_train, y_train)
y_pred3 = model3.predict(X_test)

# Step 4: Evaluate the models
def evaluate_model(y_true, y_pred, model_name):
    mse = mean_squared_error(y_true, y_pred)
    r2 = r2_score(y_true, y_pred)
    print(f"Model: {model_name}")
    print(f"Mean Squared Error: {mse:.4f}")
    print(f"R-squared: {r2:.4f}")
    print()

evaluate_model(y_test, y_pred1, "Basic Linear Regression")
evaluate_model(y_test, y_pred2, "Ridge Regression")
evaluate_model(y_test, y_pred3, "Lasso Regression")

# Step 5: Interpret the coefficients

# Interpret model 1 coefficients
def interpret_coefficients(model, feature_names):
    coef = model.coef_
    intercept = model.intercept_
    coef_df = pd.DataFrame({'Feature': feature_names, 'Coefficient': coef})
    coef_df = coef_df.sort_values(by='Coefficient', ascending=False)
    print("Model Coefficients:")
    print(coef_df)
    print(f"Intercept: {intercept:.4f}")
    print()

# Interpret for each model
interpret_coefficients(model1, X.columns)
interpret_coefficients(model2, X.columns)
interpret_coefficients(model3, X.columns)

#Explanation:
#1.Dataset Loading and Preprocessing:
#We use the California housing dataset (fetch_california_housing) from sklearn as an example. You can replace this dataset with your own dataset by loading it using pd.read_csv() or another method.
#We split the data into features (X) and the target variable (y)
#The data is split into training and testing sets using train_test_split().
#The features are standardized using StandardScaler to improve model performance.

#2.Model Creation:
#Model 1: Basic multiple linear regression using LinearRegression().
#Model 2: Ridge regression, which is a regularized linear model. The alpha parameter controls the strength of the regularization.
#Model 3: Lasso regression, another regularized linear model with alpha controlling the regularization strength.

#3.Evaluation:
#We evaluate each model using mean_squared_error and r2_score metrics, which give us an idea of how well the model is performing.

#4.Coefficient Interpretation:
#We extract the coefficients of each model and display them in a sorted manner. The coefficients tell us how much the target variable (house prices in this case) is expected to change for a one-unit change in the corresponding feature, assuming all other features remain constant.
#The intercept represents the value of the target variable when all feature values are zero.

#4..Evaluate the performance of the model using appropriate evaluation metrics on the testing dataset.

In [ ]:
# Import required libraries
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np

# Define a function to evaluate model performance
def evaluate_model_performance(y_true, y_pred, model_name):
    # Calculate MSE, RMSE, MAE, and R²
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    mae = mean_absolute_error(y_true, y_pred)
    r2 = r2_score(y_true, y_pred)

    print(f"Evaluation for {model_name}:")
    print(f"Mean Squared Error (MSE): {mse:.4f}")
    print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")
    print(f"Mean Absolute Error (MAE): {mae:.4f}")
    print(f"R-squared (R²): {r2:.4f}")
    print("-" * 50)

# Evaluate all models
evaluate_model_performance(y_test, y_pred1, "Basic Linear Regression")
evaluate_model_performance(y_test, y_pred2, "Ridge Regression")
evaluate_model_performance(y_test, y_pred3, "Lasso Regression")

#Explanation:
#1.Importing Evaluation Metrics:
#We import mean_squared_error, mean_absolute_error, r2_score from sklearn.metrics to calculate the required metrics.
#We use np.sqrt() to calculate the Root Mean Squared Error (RMSE) since it is the square root of MSE.

#2.evaluate_model_performance Function:
#This function takes the true values (y_true) and the predicted values (y_pred) as inputs, along with the model name.
#It computes the following metrics:
#MSE: Measures how much the predictions deviate from the actual values.
#RMSE: Provides an interpretable value of the average prediction error in the same units as the target variable.
#MAE: Gives the average absolute difference between actual and predicted values.
#R²: Represents how well the model explains the variance in the target variable.

#3.Evaluating Models:
#We call evaluate_model_performance() for each model (model1, model2, model3), passing the true target values (y_test) and the predicted values (y_pred1, y_pred2, y_pred3).

#5.Apply Lasso and Ridge methods on the model.

In [ ]:
from sklearn.linear_model import Lasso
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_regression
from sklearn.metrics import mean_squared_error, r2_score

# Generate a sample regression dataset
X, y = make_regression(n_samples=100, n_features=10, noise=0.1, random_state=42)

# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Apply Lasso regression
lasso_model = Lasso(alpha=0.1)  # You can adjust alpha for stronger or weaker regularization
lasso_model.fit(X_train, y_train)

# Make predictions
y_pred = lasso_model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error:", mse)
print("R-squared:", r2)

# View the coefficients
print("Lasso Coefficients:", lasso_model.coef_)

In [ ]:
# Import required libraries
from sklearn.linear_model import Ridge, Lasso
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np

# Step 1: Apply Ridge Regression (L2 Regularization)
ridge_model = Ridge(alpha=1.0)  # alpha is the regularization strength
ridge_model.fit(X_train, y_train)
ridge_pred = ridge_model.predict(X_test)

# Step 2: Apply Lasso Regression (L1 Regularization)
lasso_model = Lasso(alpha=0.1)  # alpha is the regularization strength
lasso_model.fit(X_train, y_train)
lasso_pred = lasso_model.predict(X_test)

# Step 3: Evaluate the performance of both models

def evaluate_model_performance(y_true, y_pred, model_name):
    # Calculate MSE, RMSE, MAE, and R²
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    mae = mean_absolute_error(y_true, y_pred)
    r2 = r2_score(y_true, y_pred)

    print(f"Evaluation for {model_name}:")
    print(f"Mean Squared Error (MSE): {mse:.4f}")
    print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")
    print(f"Mean Absolute Error (MAE): {mae:.4f}")
    print(f"R-squared (R²): {r2:.4f}")
    print("-" * 50)

# Evaluate both Ridge and Lasso models
evaluate_model_performance(y_test, ridge_pred, "Ridge Regression")
evaluate_model_performance(y_test, lasso_pred, "Lasso Regression")

# Step 4: Interpret the coefficients for both models

def interpret_coefficients(model, feature_names):
    coef = model.coef_
    intercept = model.intercept_
    coef_df = pd.DataFrame({'Feature': feature_names, 'Coefficient': coef})
    coef_df = coef_df.sort_values(by='Coefficient', ascending=False)
    print("Model Coefficients:")
    print(coef_df)
    print(f"Intercept: {intercept:.4f}")
    print()

# Interpret for Ridge and Lasso models
interpret_coefficients(ridge_model, X.columns)
interpret_coefficients(lasso_model, X.columns)

#What is Lasso
#Lasso (Least Absolute Shrinkage and Selection Operator) is a type of linear regression technique that incorporates L1 regularization. It is used to enhance the model's performance by preventing overfitting and performing feature selection.

#Explanation:
#1.Ridge Regression (Ridge):
#Alpha Parameter: The alpha parameter controls the strength of regularization. A larger alpha value leads to stronger regularization (smaller coefficients). You can experiment with different values of alpha to find the optimal one.
#We create a Ridge model and fit it to the training data (X_train and y_train). After fitting the model, we use it to predict the values for the test set (X_test).

#2.Lasso Regression (Lasso):
#Alpha Parameter: Like Ridge, the alpha parameter controls the regularization strength. A higher alpha value increases the regularization effect, which can result in many coefficients being reduced to zero.
#We create a Lasso model and fit it similarly to Ridge. Then, we use it to predict the test set.

#3.Model Evaluation:
#We use the evaluate_model_performance() function to evaluate both Ridge and Lasso models. The evaluation includes metrics such as:
#MSE (Mean Squared Error): Lower values are better.
#RMSE (Root Mean Squared Error): Measures the average magnitude of the errors.
#MAE (Mean Absolute Error): Gives the average of the absolute differences between actual and predicted values.
#R² (R-squared): Measures the proportion of variance explained by the model. Higher values are better (closer to 1).

#4.Interpretation of Coefficients:
#The interpret_coefficients() function extracts the coefficients of each model (Ridge and Lasso) and sorts them by magnitude. This helps to understand how each feature contributes to the model's predictions.
#For Ridge, the coefficients are usually smaller, but none of them are exactly zero (unless the regularization strength is extremely high).
#For Lasso, some coefficients might be driven to zero, effectively eliminating less important features.